### ISSUE TITLE
js-localization/messages not generated

### ISSUE THREAD

**Issue by abshammeri** [andywer/laravel-js-localization#11]
I did the following : 

> composer require andywer/js-localization:dev-laravel-5 -vvv
> composer update
> php artisan vendor:publish

changed the config file to : 

> 'messages' => ['services']

Then 

> php artisan js-localization:refresh

and I've added: 

> @include('js-localization::head')
> @yield('js-localization.head')

But still message javascript file not generated and document.write( Lang.get('services.user') ) returns error.

Did I miss anything?

**Comment by andywer** [comment]
The package does not create a messages file. The translated messages get cached using the Cache facade.

Try browsing to the route /js-localization/messages. This route should expose the translated messages encoded in JSON. Please tell me what you get when requesting this route, so we can continue debugging.

Maybe I should add a little debugging guide to the README... ;)

**Comment by andywer** [comment]
Or maybe you already meant that `/js-localization/messages` shows a 404 error?

In this case you maybe just forgot to add the service provider to your `config/app.php`.

**Comment by abshammeri** [comment]
exactly , this route /js-localization/messages shows a 404, I've added the provider to app.php

```
        /*
         * Application Service Providers...
         */
        'App\Providers\AppServiceProvider',
        'App\Providers\BusServiceProvider',
        'App\Providers\ConfigServiceProvider',
        'App\Providers\EventServiceProvider',
        'App\Providers\RouteServiceProvider',
        'App\Providers\EppServiceProvider',
        'App\Providers\MacroServiceProvider',
        'Barryvdh\DomPDF\ServiceProvider',
        'JsLocalization\JsLocalizationServiceProvider'
```

Then I did  `vendor:publish`.

By the way, I noticed that hyphen character does not work in Laravel routes?  it shows 404 !

```
Route::get('/js-localization/messages', function()
{
    return 'test';
});
```

i'm not sure if this relates some how to my issue :(. 

Thanks

**Comment by andywer** [comment]
Yeah, that's pretty strange. But I don't think that this has something to do with the hyphen.

You are using Laravel 5.0? Do other routes work?

**Comment by abshammeri** [comment]
aha .. I got it. I'm using php development server

```
cd laravel-project-folder
php -S localhost:8888 -t ./public
```

This server cannot forward request url with hyphen to Laravel? I'm not sure why? even public/index.php is not executed!

I changed your routes.php by removing the hyphens , and it works fine :

```
Route::group([ 'namespace' => '\JsLocalization\Http\Controllers' ], function()
{
    Route::get('/jslocalization/messages', 'JsLocalizationController@createJsMessages');

    Route::get('/jslocalization/localization.js', function()
    {
        $response = new StaticFileResponse( __DIR__."/../../public/js/localization.min.js" );
        $response->setPublic();
        $response->header('Content-Type', 'application/javascript');

        return $response;
    });
});

```

> php 5.6.7 , Mac 
> Laravel v5.0.27

I really don't have a clue why that change solves the issue. But it seems something related to PHP dev server!

Thanks for your time.

**Comment by andywer** [comment]
No problem. Unfortunately, I have not tryed the built-in server yet.

Would be nice if you can post a solution here if you get it to work using the built-in server.
