### ISSUE TITLE
Translation in configuration

### ISSUE THREAD

**Issue by jvv** [andywer/laravel-js-localization#13]
In my application configuration I have set a variable, which I'd like to have in my js-localization as well. It looks like the following:

Config (mysite.php):

```
return array(
    'products'   => 'Products'
);
```

In my language file (products.php) I have the following entry:

```
'products'  => Config::get('mysite.products')
```

In the packages configuration I have:

```
'messages' => array(
    'products'  => array(
        'products'
    ),
)
```

After I run:

```
php artisan js-localization:refresh
```

I do get an entry in the messages file, but it does not look like: `"products.products" : "Products"` but it shows: `"products.products" : "products.products"`

---

I think this happens because the package can't read from the configuration, or something. Can't figure out why this does not work. Is this an issue or am I doing something wrong?

To clarify - the codebase will be used on multiple sites, where Products can also be named Items (or whatever). Perhaps I'm overthinking this and there might be a better way in doing such a thing, if that is the case I'd love to know how :)

**Comment by andywer** [comment]
Hey Joost. Sounds like a feature request. Can't tell you exactly why this doesn't work, but exporting config makes sense...

I'm on vacation now, but will let you know when I'm back!

**Comment by jvv** [comment]
Thanks Andy, if I figure it out before I'll let you know :)

**Comment by andywer** [comment]
Hey Joost! Please have a look at the develop branch: https://github.com/andywer/laravel-js-localization/tree/develop
There is a new config property to specify which configuration properties you want to pass to the JS code and then use Config::get() in JS. You can optionally disable caching of these exported config properties (another config setting).

Tell me if that works for you ;)

**Comment by jvv** [comment]
Hi Andy,

I probably should have mentioned that I am using laravel-4.2 =) I will try to get it up and running next week based on your code. Thanks!

**Comment by andywer** [comment]
Hey Joost. Anything new on this topic?

**Comment by jvv** [comment]
Hi - I upgraded to Laravel 5.1 which was (for me) an easier option. I'll close this ticket.

**Comment by andywer** [comment]
Nice to hear that it worked for you :)
