### ISSUE TITLE
Upgrade to laravel 5

### ISSUE THREAD

**Issue by YannPl** [andywer/laravel-js-localization#17]
Hi !
I've been using your module a lot on my laravel 4.2 project !

We are now upgrading to Laravel 5.1 and having an issue with the cache.
Everything else is correctly upgrated and operational but when I run `php artisan js-localization:refresh` I get the following error message:

```
Refreshing the message cache...


  [InvalidArgumentException]
  Cache store [] is not defined.
```

First I thought it was an installation issue. I re-installed everything from scratch following the laravel doc guide. i doubled check every configuration etc... But I'm still having this issue.

It doesn't seem to be a laravel-js-localization bug because when I try to use cache in my own code I have the same bug ! But I'm so desperately in need for a solution that I also post here for any hint..

Does anyone already faced this kind of bug or have any idea of what to try ?

**Comment by andywer** [comment]
Hi there! Are you using the right branch: `laravel-5`?

**Comment by YannPl** [comment]
Sure, I have a more detailed issue on the laravel repo which have immediately been closed:
https://github.com/laravel/framework/issues/11702#issuecomment-169044532

You can see my composer.json, config files etc...
It seems that it's really the cache of Laravel that doesn't work but no idea of how to correct that :/

**Comment by YannPl** [comment]
Okay, I'm quite stupid I guess. Just posting the solution if someone ever falls in this "trap" like I did:
- **In Laravel 4.2**, the config key for default cache driver is `"driver" => "file"` for example
- **In Laravel 5.x**, this key is named `"default" => "file"`

While migrating, I pasted config content, key by key to check for new key / config but miss this detail. so I had `"driver" => "file"` in my 5.1 instead of `"default" => "file"`

**Comment by andywer** [comment]
Ahhh. But thank you for posting the explanation :)

Cheers
