### ISSUE TITLE
It seems it's writing locale twice

### ISSUE THREAD

**Issue by WindSaber** [andywer/laravel-js-localization#20]
I follow the indications but i hasn't work, I've reviewed the code for a while and I think tha the problem is when the plugin is creating the messages file, it writes twice the locale as you can see in the picture

![image](https://cloud.githubusercontent.com/assets/3753174/12495179/ec127b26-c053-11e5-8e9c-324f12aae5b1.png)

**Comment by andywer** [comment]
Hmm, interesting. Does not happen for me.

Could you provide an extract of a language file you export using the package?

**Comment by WindSaber** [comment]
Sure, I forgot to mention that I'm working with laravel 5.2

This is my tree 
![image](https://cloud.githubusercontent.com/assets/3753174/12620240/216a5c3a-c4e1-11e5-96cd-bf2414d164ff.png)
And a file:

```
<?php

return [
    'pool' => htmlentities('pool'),
    'Pool' => htmlentities('Pool'),
    'muestra' => htmlentities('muestra'),
    'Muestra' => htmlentities('Muestra'),
    'altaPool' => htmlentities('Alta de pool'),
    'tipoPoolMuestra' =>  htmlentities("Tipo de pool/muestra"),
    'descripcion' =>  htmlentities("Descripción"),
    'elijaCategoria' =>  htmlentities("Elija categoría"),
    'patron' =>  htmlentities("Patrón"),
    'nuevaMuestra' =>  htmlentities("Nueva muestra"),
    'editarMuestra' =>  htmlentities("Editar muestra"),
    'insInicio' =>  "Elija la fecha deseada, posteriormente seleccione algun patrón de la izquierda para ver detalle o presione el botón agregar",

];
```

**Comment by michaelstivala** [comment]
This is happening for me too. Any solutions?

**Comment by andywer** [comment]
@michaelstivala Hey Michael! Which Laravel version are you using?

**Comment by michaelstivala** [comment]
Hey Andy

I'm using version 5.2

**Comment by andywer** [comment]
I'm sorry, but I actually have no 5.2 installation using the package, code seems to be right, unit tests are green... :-/ Pretty hard for me to even reproduce at the moment.

Does someone have a fix to open a pull request?

**Comment by andywer** [comment]
Btw: Which messages have you configured to be exported?
