### ISSUE TITLE
1 command to rule them all

### ISSUE THREAD

**Issue by chlab** [andywer/laravel-js-localization#27]
As discussed in [this issue](https://github.com/andywer/laravel-js-localization/issues/26), adding a translation for JS requires these steps:
1. adding the translation
2. registering the translation for js
3. refreshing the js translation cache

Which isn't a problem when adding one translation, but during active development this can become a bit verbose.

Have you used the [philo/laravel-translate](https://github.com/PhiloNL/laravel-translate) package? It takes care of step 1 for you. You do 
`php artisan translate:add group key`
Then it asks you for each translation one by one and refreshes the appropriate files for you.

So a command that runs `translate:add`, parses and rewrites the js localization config file then refreshes the cache would make adding translations quite simple. It would however add an optional dependency for the philo/laravel-translate package.

If you agree, it might make sense to extract the actual array of translations to a separate file that is easier to generate. The config file could include this file.

What do you think? If you don't see this as part of your package I might set it up as it's own package.

**Comment by andywer** [comment]
Ahhh, I didn't know `philo/laravel-translate` before. Seems to make sense, but yes, the additional depedency is not so nice.

Hmm... What do you think of my suggestion of watching the localization files when in development mode (https://github.com/andywer/laravel-js-localization/issues/26#issuecomment-236583702)?

I think you should be able to use `laravel-translate` out-of-the-box then. It changes the localization files and `laravel-js-localization` will refresh the cache automatically.

**Comment by chlab** [comment]
Well it could be an optional dependency. If the required command is not found, print a notice that laravel-translate is required for that. Or, only register the command if laravel-translate is found. Since the package does exactly what we need it to do, the dependency is justifiable.

I'm not a fan of watching the localization files as it doesn't eliminate step 2. Also when working in JS you probably already have a watch command running and maybe don't want to run another in parallel.

It's your call :)

**Comment by andywer** [comment]
True. Step 2 is not solved then...

Yeah, sure, I am convinced ;) It's probably the best solution to make it an optional dependency and add a command to `laravel-js-localization`. I just don't really have time for it right now. But if you want to write it, no problem.

PS: Nice title 🙌

**Comment by chlab** [comment]
Awesome :)

I'll have a shot at it when copying translation keys back and forth annoy me too much :)
No promise on when though. I'll close this issue for now.

Thanks for your work!
