### ISSUE TITLE
Lang.choice() doesn't parse :count

### ISSUE THREAD

**Issue by veksen** [andywer/laravel-js-localization#30]
On Laravel, `Lang::choice()` will parse `:count`, but `Lang.choice()` doesn't:

```
Lang::choice('schedule.x-posts-filtered', 2)
// => "2 postes filtrés"

Lang.choice('schedule.x-posts-filtered', 2)
// => ":count postes filtrés"
```

Not ideal, but it can be countered with:
```
Lang.choice('schedule.x-posts-filtered', 2, {count: 2})
// => "2 postes filtrés"
```

**Comment by veksen** [comment]
Do you want a PR? It's a pretty easy fix, if count isn't passed as an argument, the second argument should replace `:count`

**Comment by andywer** [comment]
Didn't I respond to that issue? Sorry, I had a lot to do with other projects 🙈

A PR would be great! :)

**Comment by andywer** [comment]
I suppose this one has been resolved? Closing.
