### ISSUE TITLE
The artisan commands does not work with Laravel 5.5

### ISSUE THREAD

**Issue by hmazter** [andywer/laravel-js-localization#40]
The export and refresh artisan commands do not work with Laravel 5.5 since it now requires a `handle` function instead of a `fire` function on the commands.

```
Method JsLocalization\Console\ExportCommand::handle() does not exist
```

**Comment by andywer** [comment]
Hey @hmazter. Thanks for your bug report!

Unfortunately I am not able to care for this at the moment. I will add a note (request for new maintainer) to the readme.

**Comment by andywer** [comment]
Has been fixed by #41.

**Comment by hmazter** [comment]
Thanks! 😄

**Comment by romadhon-razzan** [comment]
try to rename method fire (if exist) to handle in ( ExportCommand)
