### ISSUE TITLE
Quick-fix new generateMessageFiles()

### ISSUE THREAD

**Issue by andywer** [andywer/laravel-js-localization#49]
Seems like the latest feature's code has a bug. The output JS file that we create might end up empty.

<img width="581" alt="bildschirmfoto 2018-05-03 um 20 31 32" src="https://user-images.githubusercontent.com/1842462/39596158-d23cb9ec-4f11-11e8-9b63-e6c4da57accc.png">

**Comment by andywer** [comment]
@carestad Maybe you have a quick fix at hand?

And a bit of shame on me that I didn't notice when reviewing 😉

**Comment by carestad** [comment]
Oh! Well, I suppose moving the two lines below the `if (key_exists())` into the if there would do the trick. Let me fix :)
