### ISSUE TITLE
Need to run artisan js-localization:refresh on every new translation?

### ISSUE THREAD

**Issue by m33ts4k0z** [andywer/laravel-js-localization#51]
Hello, 
I wonder if I need to run the command every time I add a new translation to the translation file.

I have 'disable_config_cache' => true but it doesn't seem to help.

Thanks

**Comment by andywer** [comment]
Hey @m33ts4k0z.

`disable_config_cache` should do the trick as far as I remember.

Just to make sure: Are you using the package's endpoints (`@yield('js-localization.head')`) or do you export files using `php artisan js-localization:export`? In the export case you need to re-export after applying any changes, of course.
