### ISSUE TITLE
Static generation getting started

### ISSUE THREAD

**Issue by jdbaculard** [andywer/laravel-js-localization#59]
I've got a problem with static generation. How I add in the <head> ?

without use @include('js-localization::head') and @yield('js-localization.head')

I use :export command
The messages.js's file is updated but it is don't use in live

**Comment by andywer** [comment]
Just include the JS code and the `messages.js` via `<script>` or include it in your JS bundle (if bundling) and you can use the localizations in your JS code.

**Comment by jdbaculard** [comment]
Thanks. Sorry but it is not working for me

    <script src="js/localization.min.js"></script>
    <script src="js/messages.js"></script>

TypeError: Cannot read property 'home.add' of undefined"

home.add it is my string

**Comment by andywer** [comment]
Any 404s? Have you configured the messages you want to export export in the config file (`messages` key) before exporting? (See readme)

**Comment by jdbaculard** [comment]
Yes I do
But after in vuejs it isn't working

**Comment by andywer** [comment]
If you are using Vue.js you are probably bundling with webpack or so. Did you put the `<script src="js/messages.js"></script>` *before* the `<script>` of your bundle?

Otherwise it's barely possible to debug that remotely, sorry.

**Comment by andywer** [comment]
@jdbaculard Have you been able to resolve that issue?

**Comment by jdbaculard** [comment]
Yes. Thank you very much

**Comment by andywer** [comment]
Awesome! :)
