### ISSUE TITLE
Laravel 5.8, Composer - No matching package found

### ISSUE THREAD

**Issue by krychu90** [andywer/laravel-js-localization#64]
Composer can't install package for laravel 5.8 (dev-laravel-5.8).
Error: 

> no matching package found

dev-laravel-5 is working.

**Comment by andywer** [comment]
Yeah, someone posted that already somewhere here (can't find it right now).

Strange thing is: Packagist shows the branch as expected... See <https://packagist.org/packages/andywer/js-localization>

**Comment by krychu90** [comment]
I did some research.

Command:
`composer show andywer/js-localization`

returns the result:

> versions : * dev-laravel-5

but command:
`composer show -a andywer/js-localization`

returns the result:

> versions : dev-develop, dev-laravel-5.8, dev-laravel-5, dev-laravel-4.2, dev-laravel-4.1, dev-laravel-4.0, dev-exportcmd

After that _composer update_ worked with dev-laravel-5.8

I dont know why, maybe some cache has been cleared :)

**Comment by andywer** [comment]
Cool! So it's safe to close the issue now?

**Comment by krychu90** [comment]
I think it's safe.
