### ISSUE TITLE
Unable to get translation to work (question on how this supposed to work)

### ISSUE THREAD

**Issue by huangism** [andywer/laravel-js-localization#69]
I am asking this because there is no explanation/example on how it actually works

I am using laravel 5.7

line in composer `"andywer/js-localization": "dev-laravel-5"`

in my messages.php I have `'test' => 'frtest'` in `lang/fr_FR` folder

in `js-localization.php` file I have :
  `'locales' => [ 'en_US', 'en_AU', 'fr_FR', 'ja_JP' ],`
  `'messages' => [ 'test' ],`
  `'disable_config_cache' => true,`
the rest are all default

in my js file I am trying to use `Lang.get( 'messages.test' )` or I tried `Lang.get( 'test' )`

This just returns the key `messages.test` or `test`

I don't know what I am doing wrong, I couldn't find any full examples on how this works so now I am stuck. Can anyone tell me how this thing actually works?

**Comment by decaluwepatrick** [comment]
I have a similar issue. I followed steps exactly as described, but always get undefined errors:

_Uncaught TypeError: Cannot read property 'about.team' of undefined
    at get (js-localization.min.js:1)_
 
when I call : `console.log(trans('en.about.team'));`

**Comment by andywer** [comment]
Sorry for the super late reply, but please refer to the README.

`messages` is supposed to be an object, not an array. Then it's `Lang.get('test')` 😉
